/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ETAN798 (https://sketchfab.com/ETAN798)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/kirby-2b54ad3ea4c7427aa1bbacbc83ea670b
title: Kirby
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/kirbo.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.surfaceShader1SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/kirbo.gltf')
